In [86]:
import pandas as pd
import numpy as np

In [87]:
코피스 = pd.read_csv("data/Medium_Theater_remove_cluster.csv")
인구수 = pd.read_csv("data/2019_행정동별 인구수.csv")[["행정구역", "2019년07월_총인구수", "2019년07월_세대수", "2019년07월_세대당 인구"]]
연령 = pd.read_csv("data/2019_행정동별 평균연령.csv")[["행정구역","2019년07월_평균연령"]]
직장인구 = pd.read_csv("data/2019_시군구별 직장인구.csv")
교통1907 = pd.read_csv("data/교통1907.csv")[['시구', '시', '구', '1907_승차', '1907_하차', '1907_철도승차', '1907_철도하차','1907_버스승차', '1907_버스하차']]
교통1908 = pd.read_csv("data/교통1908.csv")[['시구', '1908_승차', '1908_하차', '1908_철도승차', '1908_철도하차','1908_버스승차', '1908_버스하차']]
교통1909 = pd.read_csv("data/교통1909.csv")[['시구', '1909_승차', '1909_하차', '1909_철도승차', '1909_철도하차','1909_버스승차', '1909_버스하차']]
교통1910 = pd.read_csv("data/교통1910.csv")[['시구', '1910_승차', '1910_하차', '1910_철도승차', '1910_철도하차','1910_버스승차', '1910_버스하차']]
교통1911 = pd.read_csv("data/교통1911.csv")[['시구', '1911_승차', '1911_하차', '1911_철도승차', '1911_철도하차','1911_버스승차', '1911_버스하차']]
교통1912 = pd.read_csv("data/교통1912.csv")[['시구', '1912_승차', '1912_하차', '1912_철도승차', '1912_철도하차','1912_버스승차', '1912_버스하차']]
GRDP = pd.read_csv("data/GRDP.csv")
아파트 = pd.read_csv("data/아파트 매매가격지수.csv")
지방세 = pd.read_csv("data/지방세징수액.csv")

# 아파트 = 아파트.rename({"2019-07(아파트가격지수)":"2019_07","2019-08(아파트가격지수)":"2019_08","2019-09(아파트가격지수)":"2019_09","2019-10(아파트가격지수)":"2019_10","2019-11(아파트가격지수)":"2019_11","2019-12(아파트가격지수)":"2019_12"}, axis=1)
아파트.replace("-", np.nan, inplace=True)
아파트 = 아파트.dropna().reset_index()

직장인구 = 직장인구.rename({"시군구별(1)":"시", "시군구별(2)":"구", "2019.3":"직장인구수", "행정구역":"시구"}, axis=1)

#-------------
start_index = 15
end_index = 34
new_value = '세종특별자치시'

지방세.loc[start_index:end_index, '시'] = new_value

지방세['시구'] = 지방세['시'] + ' ' + 지방세['구']
#-------------
# start_index1 = 29
# end_index1 = 33

# 교통1910 = 교통1910.drop(range(start_index1, end_index1+ 1))

# 교통 및 아파트 평균값

In [88]:
아파트

,index,Unnamed: 0,시구,시,구,2019-07(아파트가격지수),2019-08(아파트가격지수),2019-09(아파트가격지수),2019-10(아파트가격지수),2019-11(아파트가격지수),2019-12(아파트가격지수),2020-01(아파트가격지수)
0,0,0,부산광역시 중구,부산광역시,중구,97.422188,97.183496,97.183496,97.183496,97.183496,97.149058,97.149058
1,1,1,부산광역시 서구,부산광역시,서구,92.59516,92.541566,92.399937,92.318269,92.318235,92.342186,92.39351
2,2,2,부산광역시 동구,부산광역시,동구,90.224154,90.224154,90.176433,90.018191,90.018191,90.131385,90.131385
3,3,3,부산광역시 영도구,부산광역시,영도구,87.208619,87.066075,87.066075,87.066075,87.066075,86.930303,86.90236
4,4,4,부산광역시 부산진구,부산광역시,부산진구,81.776145,81.52549,81.472871,81.416015,81.330596,81.343295,81.343295
...,...,...,...,...,...,...,...,...,...,...,...,...
81,136,136,경상남도 거제시,경상남도,거제시,94.023831,94.007931,93.928252,93.922586,93.842856,93.729514,93.408572
82,137,137,경상남도 양산시,경상남도,양산시,85.405552,85.188715,84.78903,84.464261,84.393326,84.202201,84.184807
83,148,148,강원도 춘천시,강원도,춘천시,87.448017,86.606137,86.063001,85.494863,84.910111,84.427332,84.003402
84,149,149,강원도 원주시,강원도,원주시,86.638554,86.228351,86.123376,86.037481,85.788792,85.695005,85.602698
85,150,150,강원도 강릉시,강원도,강릉시,77.184074,77.085603,76.829005,76.729266,76.626617,76.710757,76.706763

## 교통 평균

In [89]:
# A =pd.merge(교통1907, 교통1910, how="left", on="시구")

In [90]:
# A["1910_승차"].iloc[29] = 1435764
# A["1910_승차"].iloc[30] = 3476914
# A["1910_승차"].iloc[31] = 5111422
# A["1910_승차"].iloc[32] = 3471795
# A["1910_승차"].iloc[33] = 2917937

# A["1910_하차"].iloc[29] = 1152939
# A["1910_하차"].iloc[30] = 2958726
# A["1910_하차"].iloc[31] = 4393141
# A["1910_하차"].iloc[32] = 3076559
# A["1910_하차"].iloc[33] = 2539382

# A["1910_철도승차"].iloc[29] = 0
# A["1910_철도승차"].iloc[30] = 650294
# A["1910_철도승차"].iloc[31] = 998362
# A["1910_철도승차"].iloc[32] = 932874
# A["1910_철도승차"].iloc[33] = 560738

# A["1910_철도하차"].iloc[29] = 0
# A["1910_철도하차"].iloc[30] = 601623
# A["1910_철도하차"].iloc[31] = 1042377
# A["1910_철도하차"].iloc[32] = 901163
# A["1910_철도하차"].iloc[33] = 584346

# A["1910_버스승차"] = A["1910_승차"] - A["1910_철도승차"]
# A["1910_버스하차"] = A["1910_하차"] - A["1910_철도하차"]

In [91]:
# A.columns

In [92]:
# B = A[['시구', '시', '구', '1910_승차', '1910_하차', '1910_철도승차','1910_철도하차', '1910_버스승차', '1910_버스하차']]

In [93]:
# B.to_csv("교통1910.csv", index=False)

In [94]:
try1 = pd.merge(교통1907, 교통1908, on ="시구")
try2 = pd.merge(try1, 교통1909, on ="시구")
try3 = pd.merge(try2, 교통1910, on ="시구")
try4 = pd.merge(try3, 교통1911, on ="시구")
try5 = pd.merge(try4, 교통1912, on ="시구")

try5.head()

,시구,시,구,1907_승차,1907_하차,1907_철도승차,1907_철도하차,1907_버스승차,1907_버스하차,1908_승차,...,1911_철도승차,1911_철도하차,1911_버스승차,1911_버스하차,1912_승차,1912_하차,1912_철도승차,1912_철도하차,1912_버스승차,1912_버스하차
0,부산광역시 강서구,부산광역시,강서구,1508454,798167,804724.0,671392.0,703730.0,126775.0,1437153,...,850646.0,711777.0,713896.0,195493.0,1550510,902502,850452.0,710474.0,700058.0,192028.0
1,부산광역시 금정구,부산광역시,금정구,3619735,1710179,1045992.0,893813.0,2573743.0,816366.0,3501285,...,1059720.0,902096.0,2706460.0,1078054.0,3642835,1945456,1072724.0,908926.0,2570111.0,1036530.0
2,부산광역시 기장군,부산광역시,기장군,1291975,489091,285304.0,235221.0,1006671.0,253870.0,1258360,...,303452.0,247950.0,1001298.0,350968.0,1297225,602231,306148.0,251788.0,991077.0,350443.0
3,부산광역시 남구,부산광역시,남구,4489712,2019941,1299228.0,1138006.0,3190484.0,881935.0,4321941,...,1376327.0,1210714.0,3235968.0,1160952.0,4541877,2344085,1373578.0,1199110.0,3168299.0,1144975.0
4,부산광역시 동구,부산광역시,동구,4049055,2500145,1617129.0,1429331.0,2431926.0,1070814.0,3971277,...,1672794.0,1493873.0,2357849.0,1254907.0,4093903,2806046,1737671.0,1550714.0,2356232.0,1255332.0

In [95]:
try5["버스승차"] = (try5["1907_버스승차"] + try5["1908_버스승차"] + try5["1909_버스승차"] + try5["1910_버스승차"] + try5["1911_버스승차"] + try5["1912_버스승차"])/6
try5["버스하차"] = (try5["1907_버스하차"] + try5["1908_버스하차"] + try5["1909_버스하차"] + try5["1910_버스하차"] + try5["1911_버스하차"] + try5["1912_버스하차"])/6
try5["철도승차"] = (try5["1907_철도승차"] + try5["1908_철도승차"] + try5["1909_철도승차"] + try5["1910_철도승차"] + try5["1911_철도승차"] + try5["1912_철도승차"])/6
try5["철도하차"] = (try5["1907_철도하차"] + try5["1908_철도하차"] + try5["1909_철도하차"] + try5["1910_철도하차"] + try5["1911_철도하차"] + try5["1912_철도하차"])/6

In [96]:
대중교통 = try5[["시구", "시", "구", "버스승차", "버스하차", "철도승차", "철도하차"]]
대중교통["버스승하차"] = 대중교통["버스승차"] + 대중교통["버스하차"]
대중교통["철도승하차"] = 대중교통["철도승차"] + 대중교통["철도하차"]

<ipython-input-96-5e6228d23943>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  대중교통["버스승하차"] = 대중교통["버스승차"] + 대중교통["버스하차"]
<ipython-input-96-5e6228d23943>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  대중교통["철도승하차"] = 대중교통["철도승차"] + 대중교통["철도하차"]

In [97]:
대중교통

,시구,시,구,버스승차,버스하차,철도승차,철도하차,버스승하차,철도승하차
0,부산광역시 강서구,부산광역시,강서구,6.877017e+05,1.641650e+05,8.172995e+05,6.834927e+05,8.518667e+05,1.500792e+06
1,부산광역시 금정구,부산광역시,금정구,2.607097e+06,9.608122e+05,1.043315e+06,8.889245e+05,3.567909e+06,1.932239e+06
2,부산광역시 기장군,부산광역시,기장군,9.907893e+05,3.114340e+05,2.904668e+05,2.378752e+05,1.302223e+06,5.283420e+05
3,부산광역시 남구,부산광역시,남구,3.158830e+06,1.036189e+06,1.319761e+06,1.155389e+06,4.195019e+06,2.475150e+06
4,부산광역시 동구,부산광역시,동구,2.359904e+06,1.176714e+06,1.633994e+06,1.450878e+06,3.536619e+06,3.084872e+06
...,...,...,...,...,...,...,...,...,...
150,강원도 태백시,강원도,태백시,6.919567e+04,1.075750e+04,0.000000e+00,0.000000e+00,7.995317e+04,0.000000e+00
151,강원도 평창군,강원도,평창군,1.902717e+04,4.044500e+03,0.000000e+00,0.000000e+00,2.307167e+04,0.000000e+00
152,강원도 홍천군,강원도,홍천군,6.053350e+04,9.534333e+03,0.000000e+00,0.000000e+00,7.006783e+04,0.000000e+00
153,강원도 화천군,강원도,화천군,2.304883e+04,1.161500e+03,0.000000e+00,0.000000e+00,2.421033e+04,0.000000e+00
154,강원도 횡성군,강원도,횡성군,7.902467e+04,3.927167e+03,0.000000e+00,0.000000e+00,8.295183e+04,0.000000e+00

## 아파트 평균

In [98]:
아파트=아파트.astype({"2019-07(아파트가격지수)":"float"})
아파트=아파트.astype({"2019-08(아파트가격지수)":"float"})
아파트=아파트.astype({"2019-09(아파트가격지수)":"float"})
아파트=아파트.astype({"2019-10(아파트가격지수)":"float"})
아파트=아파트.astype({"2019-11(아파트가격지수)":"float"})
아파트=아파트.astype({"2019-12(아파트가격지수)":"float"})

In [99]:
아파트.columns

Index(['index', 'Unnamed: 0', '시구', '시', '구', '2019-07(아파트가격지수)',
       '2019-08(아파트가격지수)', '2019-09(아파트가격지수)', '2019-10(아파트가격지수)',
       '2019-11(아파트가격지수)', '2019-12(아파트가격지수)', '2020-01(아파트가격지수)'],
      dtype='object')

In [100]:
아파트["부동산가격지수"] = (아파트["2019-07(아파트가격지수)"] + 아파트["2019-08(아파트가격지수)"] + 아파트["2019-09(아파트가격지수)"] + 아파트["2019-10(아파트가격지수)"] + 아파트["2019-11(아파트가격지수)"] + 아파트["2019-12(아파트가격지수)"])/6
아파트 = 아파트[['시구', '시', '구','부동산가격지수']]

In [101]:
아파트

            시구      시     구    부동산가격지수
0     부산광역시 중구  부산광역시    중구  97.217538
1     부산광역시 서구  부산광역시    서구  92.419225
2     부산광역시 동구  부산광역시    동구  90.132085
3    부산광역시 영도구  부산광역시   영도구  87.067204
4   부산광역시 부산진구  부산광역시  부산진구  81.477402
..         ...    ...   ...        ...
81    경상남도 거제시   경상남도   거제시  93.909162
82    경상남도 양산시   경상남도   양산시  84.740514
83     강원도 춘천시    강원도   춘천시  85.824910
84     강원도 원주시    강원도   원주시  86.085260
85     강원도 강릉시    강원도   강릉시  76.860887

[86 rows x 4 columns]

# 연령 + 인구수 조인

In [104]:
test = pd.merge(연령, 인구수, how='left', on="행정구역").dropna()

In [105]:
test

,행정구역,2019년07월_평균연령,2019년07월_총인구수,2019년07월_세대수,2019년07월_세대당 인구
1,서울특별시,42.5,"9,751,415","4,308,300",2.26
2,서울특별시 종로구,44.5,"151,858","73,790",2.06
3,서울특별시 종로구 청운효자동,43.0,"12,886","5,370",2.40
4,서울특별시 종로구 사직동,44.9,"9,402","4,546",2.07
5,서울특별시 종로구 삼청동,47.3,"2,782","1,397",1.99
...,...,...,...,...,...
3815,제주특별자치도 서귀포시 서홍동,39.2,"10,505","4,247",2.47
3816,제주특별자치도 서귀포시 대륜동,41.6,"14,356","6,122",2.34
3817,제주특별자치도 서귀포시 대천동,39.9,"13,724","6,187",2.22
3818,제주특별자치도 서귀포시 중문동,42.3,"11,279","5,227",2.16
3819,제주특별자치도 서귀포시 예래동,45.9,"4,069","1,970",2.07

In [106]:
test = test[~test["행정구역"].str.contains("서울특별시|인천광역시|경기도|제주특별")]

In [107]:
test

              행정구역  2019년07월_평균연령 2019년07월_총인구수 2019년07월_세대수  2019년07월_세대당 인구
451        부산광역시             44.3     3,425,317    1,491,205             2.30
452      부산광역시 중구            49.3        42,350       23,125             1.83
453   부산광역시 중구 중앙동           48.9         1,955        1,231             1.59
454   부산광역시 중구 동광동           52.5         3,050        1,916             1.59
455   부산광역시 중구 대청동           47.9         6,814        3,501             1.95
...            ...            ...           ...          ...              ...
3769  경상남도 합천군 쌍백면           62.7         1,811        1,121             1.62
3770  경상남도 합천군 삼가면           58.8         3,395        1,911             1.78
3771  경상남도 합천군 가회면           59.8         1,870        1,062             1.76
3772  경상남도 합천군 대병면           57.7         2,155        1,215             1.77
3773  경상남도 합천군 용주면           60.9         2,289        1,301             1.76

[2567 rows x 5 columns]

연령 및 인구수 + kopis 조인

# 직장인구 + KOPIS 조인

In [108]:
코피스['시도'] = 코피스['주소'].str.split(' ').str[0]
코피스['시'] = 코피스['주소'].str.split(' ').str[1]
코피스['구'] = 코피스['주소'].str.split(' ').str[2]
코피스["시구"] = 코피스["시도"] + ' ' + 코피스["시"]

In [109]:
직장인구=직장인구[~직장인구['시구'].str.contains("서울특별시|인천광역시|경기도|제주특별")]

In [110]:
직장인구

         시    구    직장인구수         시구
26   부산광역시   소계  1117191   부산광역시 소계
27   부산광역시   중구    12205   부산광역시 중구
28   부산광역시   서구    32015   부산광역시 서구
29   부산광역시   동구    25957   부산광역시 동구
30   부산광역시  영도구    33172  부산광역시 영도구
..     ...  ...      ...        ...
258   경상남도  하동군    10309   경상남도 하동군
259   경상남도  산청군     7779   경상남도 산청군
260   경상남도  함양군     9375   경상남도 함양군
261   경상남도  거창군    15335   경상남도 거창군
262   경상남도  합천군     9544   경상남도 합천군

[183 rows x 4 columns]

In [111]:
test2 = pd.merge(코피스,직장인구[["시구","직장인구수"]], how="left", on="시구")

In [112]:
test2[test2.직장인구수.isna()]

,Unnamed: 0,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,...,일,예매건수,취소건수,무료여부,평균좌석점유율,시도,시,구,시구,직장인구수
0,0,FC222007,경상남도 창원시 의창구 중앙대로 181 (용호동),516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,...,22.215385,1.0,0.0,2.000000,0.413047,경상남도,창원시,의창구,경상남도 창원시,NaN
12,12,FC222099,경상남도 창원시 마산회원구 삼호로 135 (양덕동) 3.15아트센터,463.0,1.0,76136.448598,99.000000,99.000000,0.000000,99.000000,...,7.738318,1.0,0.0,2.000000,0.357252,경상남도,창원시,마산회원구,경상남도 창원시,NaN
15,15,FC222151,전라북도 전주시 덕진구 권삼득로 407 (덕진동2가),486.0,1.0,15625.963636,64.105455,65.834182,334.545455,99.000000,...,21.159273,1.0,0.0,2.000000,0.146495,전라북도,전주시,덕진구,전라북도 전주시,NaN
35,35,FC222466,경상남도 창원시 진해구 진해대로 325 (태백동) 진해구민센터,964.0,1.0,36132.075472,99.000000,99.000000,0.000000,99.000000,...,5.000000,1.0,0.0,2.000000,0.055000,경상남도,창원시,진해구,경상남도 창원시,NaN
58,58,FC222655,세종특별자치시 조치원읍 문예회관길 22,842.0,1.0,10557.113914,35.157289,30.381236,90.853659,99.000000,...,18.596868,1.0,0.0,1.828160,0.403005,세종특별자치시,조치원읍,문예회관길,세종특별자치시 조치원읍,NaN
60,60,FC222659,충청남도 천안시 서북구 성환읍 성진로 15,686.0,1.0,26623.865278,81.299653,60.383681,345.563889,98.566667,...,20.362500,1.0,0.0,2.000000,0.424619,충청남도,천안시,서북구,충청남도 천안시,NaN
67,67,FC222691,전라북도 전주시 완산구 팔달로 161 (경원동1가),357.0,1.0,7359.760424,10.718428,10.051412,0.000000,99.000000,...,15.967269,1.0,0.0,2.000000,0.175121,전라북도,전주시,완산구,전라북도 전주시,NaN
69,69,FC222699,전라북도 전주시 덕진구 소리로 31 (덕진동1가) 소리문화전당 소리문화전당,666.0,1.0,15261.846976,99.000000,99.000000,0.000000,99.000000,...,17.216672,1.0,0.0,2.000000,0.434398,전라북도,전주시,덕진구,전라북도 전주시,NaN
99,99,FC223313,경상북도 포항시 남구 희망대로 850 (대도동),984.0,1.0,25467.528594,66.174211,34.179951,17.001546,99.000000,...,11.635460,1.0,0.0,2.000000,0.502632,경상북도,포항시,남구,경상북도 포항시,NaN
109,109,FC223470,충청북도 청주시 서원구 예체로 118-1 (사직동),710.0,1.0,23943.384515,62.752042,63.402483,444.233910,99.000000,...,23.645541,1.0,0.0,2.000000,0.195457,충청북도,청주시,서원구,충청북도 청주시,NaN
110,110,FC223478,경상북도 포항시 남구 시청로 1 (대잠동),596.0,1.0,13566.858738,72.128668,54.451982,0.000000,99.000000,...,15.227995,1.0,0.0,1.938314,0.431902,경상북도,포항시,남구,경상북도 포항시,NaN
111,111,FC223485,전라북도 전주시 완산구 전주천동로 20 - 0 전통문화센터 전주전통문화관,300.0,1.0,17531.609195,66.948276,55.666667,3465.517241,85.482759,...,15.885057,1.0,0.0,2.000000,0.048250,전라북도,전주시,완산구,전라북도 전주시,NaN
114,114,FC223505,충청남도 천안시 동남구 성남면 종합휴양지로 185,443.0,1.0,17226.008643,91.979994,92.312580,53.861716,98.692702,...,20.152529,1.0,0.0,2.000000,0.624892,충청남도,천안시,동남구,충청남도 천안시,NaN

In [113]:
test2['직장인구수'].iloc[0] = 92508
test2['직장인구수'].iloc[12] = 64030
test2['직장인구수'].iloc[15] = 107749
test2['직장인구수'].iloc[35] = 67453
test2['직장인구수'].iloc[58] = 134250
test2['직장인구수'].iloc[60] = 158145
test2['직장인구수'].iloc[67] = 111942
test2['직장인구수'].iloc[69] = 107749
test2['직장인구수'].iloc[99] = 75475
test2['직장인구수'].iloc[109] = 71887
test2['직장인구수'].iloc[110] = 75475
test2['직장인구수'].iloc[111] = 111942
test2['직장인구수'].iloc[114] = 93554

<ipython-input-113-1ccb6e31e7e7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[0] = 92508
<ipython-input-113-1ccb6e31e7e7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[12] = 64030
<ipython-input-113-1ccb6e31e7e7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[15] = 107749
<ipython-input-113-1ccb6e31e7e7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[35] = 67453
<ipython-input-113-1ccb6e31e7e7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[58] = 134250
<ipython-input-113-1ccb6e31e7e7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[60] = 158145
<ipython-input-113-1ccb6e31e7e7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[67] = 111942
<ipython-input-113-1ccb6e31e7e7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[69] = 107749
<ipython-input-113-1ccb6e31e7e7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[99] = 75475
<ipython-input-113-1ccb6e31e7e7>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[109] = 71887
<ipython-input-113-1ccb6e31e7e7>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[110] = 75475
<ipython-input-113-1ccb6e31e7e7>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[111] = 111942
<ipython-input-113-1ccb6e31e7e7>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['직장인구수'].iloc[114] = 93554

In [114]:
test2.isna().sum()

Unnamed: 0    0
공연시설코드        0
주소            0
좌석수           0
예매/취소구분       0
예매/취소금액       0
예매/취소방식코드     0
결제수단코드        0
할인금액          0
할인종류코드        0
장당금액          0
년도_월          0
년도_월_일        0
년도            0
월             0
일             0
예매건수          0
취소건수          0
무료여부          0
평균좌석점유율       0
시도            0
시             0
구             0
시구            0
직장인구수         0
dtype: int64

# 교통 + 아파트 조인

In [115]:
대중교통아파트 = pd.merge(대중교통, 아파트[["시구", "부동산가격지수"]], how="left", on="시구")

In [116]:
대중교통아파트['부동산가격지수'].iloc[39] = 64.215197

<ipython-input-116-5c094f077727>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  대중교통아파트['부동산가격지수'].iloc[39] = 64.215197

In [117]:
대중교통아파트

,시구,시,구,버스승차,버스하차,철도승차,철도하차,버스승하차,철도승하차,부동산가격지수
0,부산광역시 강서구,부산광역시,강서구,6.877017e+05,1.641650e+05,8.172995e+05,6.834927e+05,8.518667e+05,1.500792e+06,79.975909
1,부산광역시 금정구,부산광역시,금정구,2.607097e+06,9.608122e+05,1.043315e+06,8.889245e+05,3.567909e+06,1.932239e+06,80.408518
2,부산광역시 기장군,부산광역시,기장군,9.907893e+05,3.114340e+05,2.904668e+05,2.378752e+05,1.302223e+06,5.283420e+05,77.996385
3,부산광역시 남구,부산광역시,남구,3.158830e+06,1.036189e+06,1.319761e+06,1.155389e+06,4.195019e+06,2.475150e+06,76.777625
4,부산광역시 동구,부산광역시,동구,2.359904e+06,1.176714e+06,1.633994e+06,1.450878e+06,3.536619e+06,3.084872e+06,90.132085
...,...,...,...,...,...,...,...,...,...,...
150,강원도 태백시,강원도,태백시,6.919567e+04,1.075750e+04,0.000000e+00,0.000000e+00,7.995317e+04,0.000000e+00,NaN
151,강원도 평창군,강원도,평창군,1.902717e+04,4.044500e+03,0.000000e+00,0.000000e+00,2.307167e+04,0.000000e+00,NaN
152,강원도 홍천군,강원도,홍천군,6.053350e+04,9.534333e+03,0.000000e+00,0.000000e+00,7.006783e+04,0.000000e+00,NaN
153,강원도 화천군,강원도,화천군,2.304883e+04,1.161500e+03,0.000000e+00,0.000000e+00,2.421033e+04,0.000000e+00,NaN
154,강원도 횡성군,강원도,횡성군,7.902467e+04,3.927167e+03,0.000000e+00,0.000000e+00,8.295183e+04,0.000000e+00,NaN

In [118]:
대중교통아파트.isna().sum()

시구          0
시           0
구           0
버스승차        0
버스하차        0
철도승차        0
철도하차        0
버스승하차       0
철도승하차       0
부동산가격지수    84
dtype: int64

# 대중교통아파트 + KOPIS 조인

In [119]:
test3 = pd.merge(test2, 대중교통아파트[['시구', '버스승차', '버스하차', '철도승차', '철도하차', '버스승하차', '철도승하차','부동산가격지수']], how="left", on="시구")

In [120]:
test3.isna().sum()

Unnamed: 0     0
공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
시도             0
시              0
구              0
시구             0
직장인구수          0
버스승차           3
버스하차           3
철도승차           3
철도하차           3
버스승하차          3
철도승하차          3
부동산가격지수       44
dtype: int64

In [122]:
test3["버스승차"].iloc[58] = 1.456869e+06
test3["버스하차"].iloc[58] = 1.250906e+06
test3["철도승차"].iloc[58] = 0
test3["철도하차"].iloc[58] = 0
test3["버스승하차"].iloc[58] = 2707774.5
test3["철도승하차"].iloc[58] = 0
test3["부동산가격지수"].iloc[58] = 64.215197

<ipython-input-122-ccc1dab09786>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["버스승차"].iloc[58] = 1.456869e+06
<ipython-input-122-ccc1dab09786>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["버스하차"].iloc[58] = 1.250906e+06
<ipython-input-122-ccc1dab09786>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["철도승차"].iloc[58] = 0
<ipython-input-122-ccc1dab09786>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["철도하차"].iloc[58] = 0
<ipython-input-122-ccc1dab09786>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["버스승하차"].iloc[58] = 2707774.5
<ipython-input-122-ccc1dab09786>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["철도승하차"].iloc[58] = 0
<ipython-input-122-ccc1dab09786>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3["부동산가격지수"].iloc[58] = 64.215197

In [123]:
test3[test3.철도하차.isna()]

,Unnamed: 0,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,...,구,시구,직장인구수,버스승차,버스하차,철도승차,철도하차,버스승하차,철도승하차,부동산가격지수
9,9,FC222091,경상남도 거창군 수남로 2181 거창군교육문화센터 거창군교육문화센터,715.0,1.0,10849.169417,3.881939,4.81131,0.0,99.0,...,수남로,경상남도 거창군,15335.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,70,FC222707,경상남도 함양군 함양읍 필봉산길 55,486.0,1.0,10243.354041,90.612183,90.61339,0.0,99.0,...,함양읍,경상남도 함양군,9375.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# GRDP + KOPIS 조인

In [124]:
GRDP = GRDP[["시구", "시", "구", "2019_GRDP"]]

In [127]:
test4 = pd.merge(test3, GRDP[["시구", "2019_GRDP"]], how="left", on ="시구")

In [131]:
GRDP[GRDP.시구.str.contains("세종")]

              시구      시      구  2019_GRDP
160  세종특별시 세종특별시  세종특별시  세종특별시   11855276

In [132]:
test4["2019_GRDP"].iloc[58] = 11855276

<ipython-input-132-eaf2aeef5915>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test4["2019_GRDP"].iloc[58] = 11855276

In [135]:
test4.isna().sum()

Unnamed: 0     0
공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
시도             0
시              0
구              0
시구             0
직장인구수          0
버스승차           2
버스하차           2
철도승차           2
철도하차           2
버스승하차          2
철도승하차          2
부동산가격지수       43
2019_GRDP      0
dtype: int64

# 지방세 + KOPIS

In [138]:
지방세

            시구      시    구  2019_지방세징수액
0     광주광역시 동구  광주광역시   동구    169715925
1     광주광역시 서구  광주광역시   서구    312321348
2     광주광역시 남구  광주광역시   남구    190509589
3     광주광역시 북구  광주광역시   북구    323587098
4    광주광역시 광산구  광주광역시  광산구    438722535
..         ...    ...  ...          ...
175   대구광역시 남구  대구광역시   남구    101535353
176   대구광역시 북구  대구광역시   북구    347379736
177  대구광역시 수성구  대구광역시  수성구    580945840
178  대구광역시 달서구  대구광역시  달서구    510341352
179  대구광역시 달성군  대구광역시  달성군    352116366

[180 rows x 4 columns]

In [141]:
test5 = pd.merge(test4, 지방세[["시구", "2019_지방세징수액"]], how="left", on="시구")

# 연령인구수 + KOPIS 조인 (보류)

In [145]:
test['시'] = test['행정구역'].str.split(' ').str[0]
test['구'] = test['행정구역'].str.split(' ').str[1]

test["시구"] = test["시"] + " " + test["구"]

<ipython-input-145-38a830738d66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['시'] = test['행정구역'].str.split(' ').str[0]
<ipython-input-145-38a830738d66>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['구'] = test['행정구역'].str.split(' ').str[1]
<ipython-input-145-38a830738d66>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["시구"] = test["시"] + " " + test["구"]

In [163]:
def remove_commas(s):
    return s.replace(',', '')

# '2019년07월_총인구수' 컬럼의 모든 값을 쉼표 제거 후 정수로 변환
test['2019년07월_총인구수'] = test['2019년07월_총인구수'].apply(remove_commas).astype(int)
test['2019년07월_세대수'] = test['2019년07월_세대수'].apply(remove_commas).astype(int)

<ipython-input-163-71f3319d4741>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['2019년07월_총인구수'] = test['2019년07월_총인구수'].apply(remove_commas).astype(int)
<ipython-input-163-71f3319d4741>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['2019년07월_세대수'] = test['2019년07월_세대수'].apply(remove_commas).astype(int)

In [165]:
test=test.astype({"2019년07월_총인구수":"int"})
test=test.astype({"2019년07월_세대수":"int"})

In [174]:
연령인구 = test.groupby("시구").mean()[["2019년07월_평균연령", "2019년07월_세대당 인구"]].reset_index()

<ipython-input-174-2f65e9cb2c41>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  연령인구 = test.groupby("시구").mean()[["2019년07월_평균연령", "2019년07월_세대당 인구"]].reset_index()

In [197]:
test[test.시구.str.contains("세종")]

,행정구역,2019년07월_평균연령,2019년07월_총인구수,2019년07월_세대수,2019년07월_세대당 인구,시,구,시구
1240,세종특별자치시,36.8,330298,131110,2.52,세종특별자치시,,세종특별자치시
1241,세종특별자치시,36.8,330298,131110,2.52,세종특별자치시,,세종특별자치시
1242,세종특별자치시,36.8,330298,131110,2.52,세종특별자치시,,세종특별자치시
1243,세종특별자치시,36.8,330298,131110,2.52,세종특별자치시,,세종특별자치시
1244,세종특별자치시 조치원읍,41.7,43659,19391,2.25,세종특별자치시,,세종특별자치시
1245,세종특별자치시 연기면,50.2,2620,1477,1.77,세종특별자치시,,세종특별자치시
1246,세종특별자치시 연동면,53.7,3235,1682,1.92,세종특별자치시,,세종특별자치시
1247,세종특별자치시 부강면,47.4,6380,3273,1.95,세종특별자치시,,세종특별자치시
1248,세종특별자치시 금남면,51.9,8883,4538,1.96,세종특별자치시,,세종특별자치시
1249,세종특별자치시 장군면,48.4,6232,3407,1.83,세종특별자치시,,세종특별자치시
1250,세종특별자치시 연서면,49.8,7678,3904,1.97,세종특별자치시,,세종특별자치시
1251,세종특별자치시 전의면,50.4,5944,3084,1.93,세종특별자치시,,세종특별자치시
1252,세종특별자치시 전동면,54.9,3798,2149,1.77,세종특별자치시,,세종특별자치시
1253,세종특별자치시 소정면,48.6,2625,1250,2.10,세종특별자치시,,세종특별자치시
1254,세종특별자치시 한솔동,33.9,19239,6272,3.07,세종특별자치시,,세종특별자치시
1255,세종특별자치시 새롬동,32.6,49872,19109,2.61,세종특별자치시,,세종특별자치시
1256,세종특별자치시 도담동,34.5,32218,13187,2.44,세종특별자치시,,세종특별자치시
1257,세종특별자치시 아름동,32.6,23875,7639,3.13,세종특별자치시,,세종특별자치시
1258,세종특별자치시 종촌동,33.4,29810,10678,2.79,세종특별자치시,,세종특별자치시
1259,세종특별자치시 고운동,32.7,33222,11333,2.93,세종특별자치시,,세종특별자치시
1260,세종특별자치시 소담동,32.8,22933,8570,2.68,세종특별자치시,,세종특별자치시
1261,세종특별자치시 보람동,33.4,17756,6335,2.80,세종특별자치시,,세종특별자치시
1262,세종특별자치시 대평동,34.5,10319,3832,2.69,세종특별자치시,,세종특별자치시

In [175]:
인구수세대수 = test.groupby("시구").sum()[["2019년07월_총인구수", "2019년07월_세대수"]].reset_index()

<ipython-input-175-e1e3cf98484f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  인구수세대수 = test.groupby("시구").sum()[["2019년07월_총인구수", "2019년07월_세대수"]].reset_index()

In [177]:
인구 = pd.merge(연령인구, 인구수세대수, how="left", on="시구")

In [179]:
인구.시구.value_counts()

강원도         1
전라남도 신안군    1
전라남도 광양시    1
전라남도 구례군    1
전라남도 나주시    1
           ..
경상북도 청송군    1
경상북도 칠곡군    1
경상북도 포항시    1
광주광역시       1
충청북도 충주시    1
Name: 시구, Length: 173, dtype: int64

In [181]:
total = pd.merge(test5, 인구, how="left", on="시구")

In [199]:
total["2019년07월_평균연령"].iloc[58] = 36.8
total["2019년07월_세대당 인구"].iloc[58] = 2.52
total["2019년07월_총인구수"].iloc[58] = 330298
total["2019년07월_세대수"].iloc[58] = 131110

<ipython-input-199-b70de6aacf15>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total["2019년07월_평균연령"].iloc[58] = 36.8
<ipython-input-199-b70de6aacf15>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total["2019년07월_세대당 인구"].iloc[58] = 2.52
<ipython-input-199-b70de6aacf15>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total["2019년07월_총인구수"].iloc[58] = 330298
<ipython-input-199-b70de6aacf15>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total["2019년07월_세대수"].iloc[58] = 131110

In [201]:
total.isna().sum()

Unnamed: 0          0
공연시설코드              0
주소                  0
좌석수                 0
예매/취소구분             0
예매/취소금액             0
예매/취소방식코드           0
결제수단코드              0
할인금액                0
할인종류코드              0
장당금액                0
년도_월                0
년도_월_일              0
년도                  0
월                   0
일                   0
예매건수                0
취소건수                0
무료여부                0
평균좌석점유율             0
시도                  0
시                   0
구                   0
시구                  0
직장인구수               0
버스승차                2
버스하차                2
철도승차                2
철도하차                2
버스승하차               2
철도승하차               2
부동산가격지수            43
2019_GRDP           0
2019_지방세징수액         0
2019년07월_평균연령       0
2019년07월_세대당 인구     0
2019년07월_총인구수       0
2019년07월_세대수        0
dtype: int64

In [207]:
# total.to_csv("join1.csv", index=False)

# 최종 조인

In [208]:
j1 = pd.read_csv("data/join1.csv")
j2 = pd.read_csv("data/join2.csv")

In [225]:
are_equal =  list(j1['공연시설코드'].values) == list(j2['공연시설코드'].values)  # 두 배열이 일치하는지 여부 확인

if are_equal:
    print("두 배열은 순서대로 일치합니다.")
else:
    print("두 배열은 순서대로 일치하지 않습니다.")

두 배열은 순서대로 일치합니다.

In [226]:
j2['주소'] = j1['주소']

In [212]:
j1.isna().sum()

Unnamed: 0          0
공연시설코드              0
주소                  0
좌석수                 0
예매/취소구분             0
예매/취소금액             0
예매/취소방식코드           0
결제수단코드              0
할인금액                0
할인종류코드              0
장당금액                0
년도_월                0
년도_월_일              0
년도                  0
월                   0
일                   0
예매건수                0
취소건수                0
무료여부                0
평균좌석점유율             0
시도                  0
시                   0
구                   0
시구                  0
직장인구수               0
버스승차                2
버스하차                2
철도승차                2
철도하차                2
버스승하차               2
철도승하차               2
부동산가격지수            43
2019_GRDP           0
2019_지방세징수액         0
2019년07월_평균연령       0
2019년07월_세대당 인구     0
2019년07월_총인구수       0
2019년07월_세대수        0
dtype: int64

In [230]:
#'주차장', '정류장', '지하철출구', '터미널', '영화상영관','박물관미술관', '도서관', '면적10000이상공원'

마지막 = pd.merge(j1, j2[['주소', '주차장', '정류장', '지하철출구', '터미널', '영화상영관','박물관미술관', '도서관', '면적10000이상공원']], how="left", on="주소")

In [232]:
마지막.columns

Index(['Unnamed: 0', '공연시설코드', '주소', '좌석수', '예매/취소구분', '예매/취소금액', '예매/취소방식코드',
       '결제수단코드', '할인금액', '할인종류코드', '장당금액', '년도_월', '년도_월_일', '년도', '월', '일',
       '예매건수', '취소건수', '무료여부', '평균좌석점유율', '시도', '시', '구', '시구', '직장인구수',
       '버스승차', '버스하차', '철도승차', '철도하차', '버스승하차', '철도승하차', '부동산가격지수',
       '2019_GRDP', '2019_지방세징수액', '2019년07월_평균연령', '2019년07월_세대당 인구',
       '2019년07월_총인구수', '2019년07월_세대수', '주차장', '정류장', '지하철출구', '터미널', '영화상영관',
       '박물관미술관', '도서관', '면적10000이상공원'],
      dtype='object')

In [234]:
마지막=마지막.drop(["Unnamed: 0"], axis=1)
마지막=마지막.rename({"2019_지방세징수액":"지방세징수액", "2019_GRDP":"GRDP", "2019년07월_평균연령":"평균연령", "2019년07월_세대당 인구":"세대당인구", "2019년07월_총인구수":"총인구수", "2019년07월_세대수":"세대수"},axis=1)

In [244]:
마지막.isna().sum()

공연시설코드          0
주소              0
좌석수             0
예매/취소구분         0
예매/취소금액         0
예매/취소방식코드       0
결제수단코드          0
할인금액            0
할인종류코드          0
장당금액            0
년도_월            0
년도_월_일          0
년도              0
월               0
일               0
예매건수            0
취소건수            0
무료여부            0
평균좌석점유율         0
시도              0
시               0
구               0
시구              0
직장인구수           0
버스승차            2
버스하차            2
철도승차            2
철도하차            2
버스승하차           2
철도승하차           2
부동산가격지수        43
GRDP            0
지방세징수액          0
평균연령            0
세대당인구           0
총인구수            0
세대수             0
주차장             1
정류장             1
지하철출구           1
터미널             1
영화상영관           1
박물관미술관          1
도서관             1
면적10000이상공원     1
dtype: int64

In [237]:
마지막.columns

Index(['공연시설코드', '주소', '좌석수', '예매/취소구분', '예매/취소금액', '예매/취소방식코드', '결제수단코드',
       '할인금액', '할인종류코드', '장당금액', '년도_월', '년도_월_일', '년도', '월', '일', '예매건수',
       '취소건수', '무료여부', '평균좌석점유율', '시도', '시', '구', '시구', '직장인구수', '버스승차',
       '버스하차', '철도승차', '철도하차', '버스승하차', '철도승하차', '부동산가격지수', 'GRDP', '지방세징수액',
       '평균연령', '세대당인구', '총인구수', '세대수', '주차장', '정류장', '지하철출구', '터미널', '영화상영관',
       '박물관미술관', '도서관', '면적10000이상공원'],
      dtype='object')

In [243]:
# 주차장	정류장	지하철출구	터미널	영화상영관	박물관미술관	도서관	면적10000이상공원
# 대전 0	4	0	0	0	6	0	2 [107]
# 울산 0	6	0	0	0	0	0	4 [117]

마지막["주차장"].iloc[107] = 0
마지막["정류장"].iloc[107] = 4
마지막["지하철출구"].iloc[107] = 0
마지막["터미널"].iloc[107] = 0
마지막["영화상영관"].iloc[107] = 0
마지막["박물관미술관"].iloc[107] = 6
마지막["도서관"].iloc[107] = 0
마지막["면적10000이상공원"].iloc[107] = 2

마지막["주차장"].iloc[117] = 0
마지막["정류장"].iloc[117] = 6
마지막["지하철출구"].iloc[117] = 0
마지막["터미널"].iloc[117] = 0
마지막["영화상영관"].iloc[117] = 0
마지막["박물관미술관"].iloc[117] = 0
마지막["도서관"].iloc[117] = 0
마지막["면적10000이상공원"].iloc[117] = 4

<ipython-input-243-c2c4f57417a6>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["주차장"].iloc[107] = 0
<ipython-input-243-c2c4f57417a6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["정류장"].iloc[107] = 4
<ipython-input-243-c2c4f57417a6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["지하철출구"].iloc[107] = 0
<ipython-input-243-c2c4f57417a6>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["터미널"].iloc[107] = 0
<ipython-input-243-c2c4f57417a6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["영화상영관"].iloc[107] = 0
<ipython-input-243-c2c4f57417a6>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["박물관미술관"].iloc[107] = 6
<ipython-input-243-c2c4f57417a6>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["도서관"].iloc[107] = 0
<ipython-input-243-c2c4f57417a6>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["면적10000이상공원"].iloc[107] = 2
<ipython-input-243-c2c4f57417a6>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["주차장"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["정류장"].iloc[117] = 6
<ipython-input-243-c2c4f57417a6>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["지하철출구"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["터미널"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["영화상영관"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["박물관미술관"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["도서관"].iloc[117] = 0
<ipython-input-243-c2c4f57417a6>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  마지막["면적10000이상공원"].iloc[117] = 4

In [245]:
# 마지막.to_csv("중극장조인최종데이터.csv", index=False)

In [250]:
마지막[마지막.도서관.isna()][["주소", '주차장', '정류장', '지하철출구', '터미널', '영화상영관','박물관미술관', '도서관', '면적10000이상공원']]

,주소,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
140,광주광역시 북구 용봉로 77 (용봉동),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [251]:
마지막[마지막.철도승차.isna()][['주소', '버스승차', '버스하차', '철도승차', '철도하차', '버스승하차', '철도승하차']]

,주소,버스승차,버스하차,철도승차,철도하차,버스승하차,철도승하차
9,경상남도 거창군 수남로 2181 거창군교육문화센터 거창군교육문화센터,NaN,NaN,NaN,NaN,NaN,NaN
70,경상남도 함양군 함양읍 필봉산길 55,NaN,NaN,NaN,NaN,NaN,NaN