In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/Medium_Theater_remove_cluster.csv').drop("Unnamed: 0", axis=1)
중극장조인후 = pd.read_csv('data/중극장조인후.csv', encoding = "cp949")
전체면적대비도로면적 = pd.read_csv('data/전체면적대비도로면적.csv', encoding = "cp949")
검색량합계및평균 = pd.read_csv('data/검색량합계및평균.csv', encoding = "cp949")

In [4]:
df['주소']=df['주소'].str.rstrip()

# 중극장조인후.csv파일과 KOPIS 데이터 조인

In [5]:
중극장조인후 = 중극장조인후.rename({'field1':'주소'}, axis = 1)[['주소', '주차장', '정류장', '지하철출구', '터미널', '영화상영관', '박물관미술관','도서관', '면적10000이상공원']]
중극장조인후

,주소,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
0,강원도 화천군 화천읍 상승로 91,16,8,0,1,0,0,2,1
1,강원도 횡성군 횡성읍 문예로 75,1,2,0,1,0,0,2,1
2,경상북도 포항시 남구 행복길 120 (효자동),0,9,0,1,0,0,0,0
3,강원도 홍천군 홍천읍 설악로 1792,0,2,0,0,0,1,0,1
4,강원도 원주시 동부순환로 200(반곡동),0,17,0,0,9,0,0,0
...,...,...,...,...,...,...,...,...,...
289,전라남도 강진군 강진읍 영랑로1길 9,6,11,0,1,0,1,1,1
290,충청북도 청주시 서원구 서부로 1428 (성화동),0,16,0,0,0,0,0,0
291,강원도 춘천시 방송길 109,20,17,1,3,7,0,2,14
292,부산광역시 수영구 구락로123번길 20 (망미동),0,25,0,1,0,0,1,3
293,경상남도 창원시 마산회원구 삼호로 135 (양덕동),0,6,0,1,0,0,1,3

In [6]:
중극장조인후[중극장조인후.주소.str.contains("강원도 태백시 태붐로 21")]

                주소  주차장  정류장  지하철출구  터미널  영화상영관  박물관미술관  도서관  면적10000이상공원
36  강원도 태백시 태붐로 21    8   13      0    0      2       0    1            2

In [7]:
중극장조인후[중극장조인후.주소.str.contains("광주광역시 북구")]

,주소,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
114,광주광역시 북구 북문대로 60 (운암동),2,9,0,0,0,1,1,2
238,광주광역시 북구 하서로 299 (양산동),0,14,0,0,0,0,1,1
248,광주광역시 북구 필문대로 55 (풍향동),1,8,0,0,0,1,1,5
254,광주광역시 북구 첨단과기로176번길 27 (오룡동),0,13,0,0,20,0,0,4
258,광주광역시 북구 능안로30번길 5(오치동),2,5,0,0,0,0,0,2

In [8]:
df['주소'] = df['주소'].str[:21]
중극장조인후['주소'] = 중극장조인후['주소'].str[:21]

In [9]:
test1 = pd.merge(df,중극장조인후, how='left', on='주소')

In [10]:
test1[test1.주소.str.contains("울산광역시 울주군 범서읍 천상중앙길 3")]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,무료여부,평균좌석점유율,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
104,FC223391,울산광역시 울주군 범서읍 천상중앙길 3,387.0,1.0,15045.714286,22.06,23.937143,0.0,99.0,15045.714286,...,2.0,0.097374,1.0,10.0,0.0,0.0,0.0,0.0,1.0,0.0
105,FC223391,울산광역시 울주군 범서읍 천상중앙길 3,387.0,1.0,15045.714286,22.06,23.937143,0.0,99.0,15045.714286,...,2.0,0.097374,1.0,10.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
test1 = test1.drop([105], axis = 0)

In [12]:
test1

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,무료여부,평균좌석점유율,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,2.000000,0.413047,0.0,10.0,0.0,0.0,13.0,0.0,1.0,1.0
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,2.000000,0.252000,1.0,27.0,0.0,0.0,0.0,0.0,1.0,1.0
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,1.890421,0.930519,1.0,1.0,0.0,0.0,13.0,0.0,0.0,6.0
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,1.937807,0.217245,3.0,26.0,22.0,0.0,9.0,0.0,0.0,2.0
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,2.000000,0.244995,0.0,30.0,14.0,0.0,17.0,3.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,2.000000,0.118333,2.0,12.0,0.0,0.0,12.0,0.0,1.0,2.0
138,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,2.000000,0.080290,2.0,6.0,0.0,0.0,2.0,0.0,0.0,1.0
139,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,2.000000,0.002333,0.0,3.0,0.0,0.0,4.0,3.0,1.0,2.0
140,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,2.000000,1.062000,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
141,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,2.000000,0.393000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
test1.주소.value_counts()

경상남도 창원시 의창구 중앙대로 181    1
전라남도 목포시 남농로 102 (용해동    1
경상남도 김해시 율하2로 210 (율하    1
대전광역시 중구 뿌리공원로 45 (안영    1
전라북도 고창군 성송면 향산1길 106    1
                        ..
강원도 속초시 번영로 155 (영랑동)    1
대구광역시 달서구 앞산순환로 180 (    1
대전광역시 서구 둔산대로 201 (만년    1
광주광역시 서구 무진대로 904 (광천    1
광주광역시 북구 용봉로 77 (용봉동)    1
Name: 주소, Length: 141, dtype: int64

In [14]:
test1.isna().sum()

공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
주차장            5
정류장            5
지하철출구          5
터미널            5
영화상영관          5
박물관미술관         5
도서관            5
면적10000이상공원    5
dtype: int64

In [15]:
중극장조인후[중극장조인후.주소.str.contains('전라북도 고창군 고창읍 모양성로|강원도 태백시 태붐로 21|대전광역시 유성구 대학로 99|울산광역시 중구 종가로 405|광주광역시 북구 용봉')]

,주소,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
36,강원도 태백시 태붐로 21,8,13,0,0,2,0,1,2
43,대전광역시 유성구 대학로 99,0,4,0,0,0,6,0,2
86,울산광역시 중구 종가로 405,0,6,0,0,0,0,0,4
259,전라북도 고창군 고창읍 모양성로 11,5,5,0,1,2,2,3,3

In [16]:
test1['주차장'].iloc[14] = 5
test1['정류장'].iloc[14] = 5
test1['지하철출구'].iloc[14] = 0
test1['터미널'].iloc[14] = 1
test1['영화상영관'].iloc[14] = 2
test1['박물관미술관'].iloc[14] = 2
test1['도서관'].iloc[14] = 3
test1['면적10000이상공원'].iloc[14] = 3

<ipython-input-16-e6dbef63fc99>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['주차장'].iloc[14] = 5
<ipython-input-16-e6dbef63fc99>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['정류장'].iloc[14] = 5
<ipython-input-16-e6dbef63fc99>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['지하철출구'].iloc[14] = 0
<ipython-input-16-e6dbef63fc99>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['터미널'].iloc[14] = 1
<ipython-input-16-e6dbef63fc99>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['영화상영관'].iloc[14] = 2
<ipython-input-16-e6dbef63fc99>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['박물관미술관'].iloc[14] = 2
<ipython-input-16-e6dbef63fc99>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['도서관'].iloc[14] = 3
<ipython-input-16-e6dbef63fc99>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['면적10000이상공원'].iloc[14] = 3

In [17]:
test1['주차장'].iloc[45] = 8
test1['정류장'].iloc[45] = 13
test1['지하철출구'].iloc[45] = 0
test1['터미널'].iloc[45] = 0
test1['영화상영관'].iloc[45] = 2
test1['박물관미술관'].iloc[45] = 0
test1['도서관'].iloc[45] = 1
test1['면적10000이상공원'].iloc[45] = 2

<ipython-input-17-4af6a4952a48>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['주차장'].iloc[45] = 8
<ipython-input-17-4af6a4952a48>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['정류장'].iloc[45] = 13
<ipython-input-17-4af6a4952a48>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['지하철출구'].iloc[45] = 0
<ipython-input-17-4af6a4952a48>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['터미널'].iloc[45] = 0
<ipython-input-17-4af6a4952a48>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['영화상영관'].iloc[45] = 2
<ipython-input-17-4af6a4952a48>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['박물관미술관'].iloc[45] = 0
<ipython-input-17-4af6a4952a48>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['도서관'].iloc[45] = 1
<ipython-input-17-4af6a4952a48>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['면적10000이상공원'].iloc[45] = 2

In [18]:
test1['주차장'].iloc[108] = 0
test1['정류장'].iloc[108] = 4
test1['지하철출구'].iloc[108] = 0
test1['터미널'].iloc[108] = 0
test1['영화상영관'].iloc[108] = 0
test1['박물관미술관'].iloc[108] = 6
test1['도서관'].iloc[108] = 0
test1['면적10000이상공원'].iloc[108] = 2

<ipython-input-18-df1fefd5a071>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['주차장'].iloc[108] = 0
<ipython-input-18-df1fefd5a071>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['정류장'].iloc[108] = 4
<ipython-input-18-df1fefd5a071>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['지하철출구'].iloc[108] = 0
<ipython-input-18-df1fefd5a071>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['터미널'].iloc[108] = 0
<ipython-input-18-df1fefd5a071>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['영화상영관'].iloc[108] = 0
<ipython-input-18-df1fefd5a071>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['박물관미술관'].iloc[108] = 6
<ipython-input-18-df1fefd5a071>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['도서관'].iloc[108] = 0
<ipython-input-18-df1fefd5a071>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['면적10000이상공원'].iloc[108] = 2

In [19]:
test1['주차장'].iloc[118] = 0
test1['정류장'].iloc[118] = 6
test1['지하철출구'].iloc[118] = 0
test1['터미널'].iloc[118] = 0
test1['영화상영관'].iloc[118] = 0
test1['박물관미술관'].iloc[118] = 0
test1['도서관'].iloc[118] = 0
test1['면적10000이상공원'].iloc[118] = 4

<ipython-input-19-d55093786177>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['주차장'].iloc[118] = 0
<ipython-input-19-d55093786177>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['정류장'].iloc[118] = 6
<ipython-input-19-d55093786177>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['지하철출구'].iloc[118] = 0
<ipython-input-19-d55093786177>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['터미널'].iloc[118] = 0
<ipython-input-19-d55093786177>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['영화상영관'].iloc[118] = 0
<ipython-input-19-d55093786177>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['박물관미술관'].iloc[118] = 0
<ipython-input-19-d55093786177>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['도서관'].iloc[118] = 0
<ipython-input-19-d55093786177>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test1['면적10000이상공원'].iloc[118] = 4

In [20]:
test1[test1['도서관'].isna()]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,무료여부,평균좌석점유율,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
108,FC223418,대전광역시 유성구 대학로 99 충남대학,450.0,1.0,26701.073164,71.052158,72.364819,222.577879,99.000000,26923.651043,...,2.000000,0.921516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,FC223540,"울산광역시 중구 종가로 405 성안동,",499.0,1.0,7004.610951,99.000000,47.505764,387.319885,3.110663,7391.930836,...,1.537464,0.355777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,2.000000,0.393000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* 결론 : 광주광역시 북구 용봉로 77은 중극장조인후에서 데이터가 아예 없음

# 도로면적조인

In [21]:
test1

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,무료여부,평균좌석점유율,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,2.000000,0.413047,0.0,10.0,0.0,0.0,13.0,0.0,1.0,1.0
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,2.000000,0.252000,1.0,27.0,0.0,0.0,0.0,0.0,1.0,1.0
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,1.890421,0.930519,1.0,1.0,0.0,0.0,13.0,0.0,0.0,6.0
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,1.937807,0.217245,3.0,26.0,22.0,0.0,9.0,0.0,0.0,2.0
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,2.000000,0.244995,0.0,30.0,14.0,0.0,17.0,3.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,2.000000,0.118333,2.0,12.0,0.0,0.0,12.0,0.0,1.0,2.0
138,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,2.000000,0.080290,2.0,6.0,0.0,0.0,2.0,0.0,0.0,1.0
139,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,2.000000,0.002333,0.0,3.0,0.0,0.0,4.0,3.0,1.0,2.0
140,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,2.000000,1.062000,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
141,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,2.000000,0.393000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
test1['시도'] = test1['주소'].str.split(' ').str[0]
test1['시'] = test1['주소'].str.split(' ').str[1]
test1['구'] = test1['주소'].str.split(' ').str[2]

In [23]:
test1

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원,시도,시,구
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,10.0,0.0,0.0,13.0,0.0,1.0,1.0,경상남도,창원시,의창구
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,27.0,0.0,0.0,0.0,0.0,1.0,1.0,부산광역시,영도구,함지로79번길
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,1.0,0.0,0.0,13.0,0.0,0.0,6.0,전라남도,여수시,예울마루로
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,26.0,22.0,0.0,9.0,0.0,0.0,2.0,부산광역시,북구,금곡대로46번길
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,30.0,14.0,0.0,17.0,3.0,1.0,2.0,부산광역시,해운대구,양운로
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,12.0,0.0,0.0,12.0,0.0,1.0,2.0,전라북도,군산시,대학로
138,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,6.0,0.0,0.0,2.0,0.0,0.0,1.0,경상북도,울진군,울진읍
139,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,3.0,0.0,0.0,4.0,3.0,1.0,2.0,강원도,정선군,정선읍
140,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,광주광역시,광산구,상무대로
141,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,광주광역시,북구,용봉로

In [24]:
test1["시군구"] = test1["시도"] + " " + test1["시"]
test1

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,0.0,0.0,13.0,0.0,1.0,1.0,경상남도,창원시,의창구,경상남도 창원시
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,0.0,0.0,0.0,0.0,1.0,1.0,부산광역시,영도구,함지로79번길,부산광역시 영도구
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,0.0,0.0,13.0,0.0,0.0,6.0,전라남도,여수시,예울마루로,전라남도 여수시
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,22.0,0.0,9.0,0.0,0.0,2.0,부산광역시,북구,금곡대로46번길,부산광역시 북구
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,14.0,0.0,17.0,3.0,1.0,2.0,부산광역시,해운대구,양운로,부산광역시 해운대구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,0.0,0.0,12.0,0.0,1.0,2.0,전라북도,군산시,대학로,전라북도 군산시
138,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,0.0,0.0,2.0,0.0,0.0,1.0,경상북도,울진군,울진읍,경상북도 울진군
139,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,0.0,0.0,4.0,3.0,1.0,2.0,강원도,정선군,정선읍,강원도 정선군
140,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,0.0,0.0,0.0,0.0,0.0,0.0,광주광역시,광산구,상무대로,광주광역시 광산구
141,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,NaN,NaN,NaN,NaN,NaN,NaN,광주광역시,북구,용봉로,광주광역시 북구

In [25]:
전체면적대비도로면적

          시군구  전체면적대비도로면적
0     강원도 강릉시    1.130609
1     강원도 고성군    0.546782
2     강원도 동해시    3.660487
3     강원도 삼척시    0.702492
4     강원도 속초시    3.109081
..        ...         ...
156  충청북도 제천시    0.636323
157  충청북도 증평군    3.395634
158  충청북도 진천군    1.543855
159  충청북도 청주시    3.423236
160  충청북도 충주시    1.752798

[161 rows x 2 columns]

In [26]:
test2 = pd.merge(test1,전체면적대비도로면적, how='left', on='시군구')

In [27]:
전체면적대비도로면적[전체면적대비도로면적.시군구.str.contains("세종특별")]

                시군구  전체면적대비도로면적
93  세종특별자치시 세종특별자치시    6.315472

In [28]:
test2[test2.전체면적대비도로면적.isna()]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적
58,FC222655,세종특별자치시 조치원읍 문예회관길 22,842.0,1.0,10557.113914,35.157289,30.381236,90.853659,99.0,10647.967572,...,1.0,5.0,0.0,1.0,2.0,세종특별자치시,조치원읍,문예회관길,세종특별자치시 조치원읍,NaN

In [29]:
test2['전체면적대비도로면적'].iloc[62] = 6.315472

<ipython-input-29-9bd72bf0ddcf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test2['전체면적대비도로면적'].iloc[62] = 6.315472

In [30]:
test2['전체면적대비도로면적'].iloc[62]

6.315472

In [31]:
test2.isna().sum()

공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
주차장            3
정류장            3
지하철출구          3
터미널            3
영화상영관          3
박물관미술관         3
도서관            3
면적10000이상공원    3
시도             0
시              0
구              0
시군구            0
전체면적대비도로면적     1
dtype: int64

# 검색량조인

In [32]:
검색량합계및평균

              시군구   검색량합계         검색량평균
0         강원도 강릉시  201796   5310.421053
1         강원도 고성군    4616    307.733333
2         강원도 동해시   13170   1463.333333
3         강원도 삼척시    7634    763.400000
4         강원도 속초시   20102   2010.200000
..            ...     ...           ...
166  충청북도 청주시 상당구   16062   1003.875000
167  충청북도 청주시 서원구  249648  16643.200000
168  충청북도 청주시 청원구   11188   1118.800000
169  충청북도 청주시 흥덕구   11541    887.769231
170      충청북도 충주시   11117    653.941176

[171 rows x 3 columns]

In [33]:
test2

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,0.0,13.0,0.0,1.0,1.0,경상남도,창원시,의창구,경상남도 창원시,4.436285
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,0.0,0.0,0.0,1.0,1.0,부산광역시,영도구,함지로79번길,부산광역시 영도구,7.076850
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,0.0,13.0,0.0,0.0,6.0,전라남도,여수시,예울마루로,전라남도 여수시,3.016880
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,0.0,9.0,0.0,0.0,2.0,부산광역시,북구,금곡대로46번길,부산광역시 북구,3.153287
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,0.0,17.0,3.0,1.0,2.0,부산광역시,해운대구,양운로,부산광역시 해운대구,3.567653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,0.0,12.0,0.0,1.0,2.0,전라북도,군산시,대학로,전라북도 군산시,3.509188
137,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,0.0,2.0,0.0,0.0,1.0,경상북도,울진군,울진읍,경상북도 울진군,0.665245
138,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,0.0,4.0,3.0,1.0,2.0,강원도,정선군,정선읍,강원도 정선군,0.464745
139,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,0.0,0.0,0.0,0.0,0.0,광주광역시,광산구,상무대로,광주광역시 광산구,1.898192
140,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,NaN,NaN,NaN,NaN,NaN,광주광역시,북구,용봉로,광주광역시 북구,3.260276

In [34]:
test3 = pd.merge(test2, 검색량합계및평균, how = 'left', on = '시군구')

In [35]:
test3

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적,검색량합계,검색량평균
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,0.0,1.0,1.0,경상남도,창원시,의창구,경상남도 창원시,4.436285,NaN,NaN
1,FC222040,부산광역시 영도구 함지로79번길 6 (,428.0,1.0,37037.037037,99.000000,99.000000,0.000000,99.000000,37037.037037,...,0.0,1.0,1.0,부산광역시,영도구,함지로79번길,부산광역시 영도구,7.076850,52470.0,5830.000000
2,FC222048,전라남도 여수시 예울마루로 100 (시,302.0,1.0,17324.854681,99.000000,99.000000,0.000000,99.000000,17324.854681,...,0.0,0.0,6.0,전라남도,여수시,예울마루로,전라남도 여수시,3.016880,10943.0,643.705882
3,FC222049,부산광역시 북구 금곡대로46번길 50,345.0,1.0,10706.324059,81.132570,82.085925,85.924714,99.000000,10792.248773,...,0.0,0.0,2.0,부산광역시,북구,금곡대로46번길,부산광역시 북구,3.153287,19354.0,1759.454545
4,FC222054,부산광역시 해운대구 양운로 97 (좌동,458.0,1.0,15950.909306,78.856958,79.165877,396.585523,98.855235,16347.494830,...,3.0,1.0,2.0,부산광역시,해운대구,양운로,부산광역시 해운대구,3.567653,190690.0,7334.230769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,FC224381,전라북도 군산시 대학로 330 (나운동,330.0,1.0,12000.000000,99.000000,99.000000,0.000000,99.000000,12000.000000,...,0.0,1.0,2.0,전라북도,군산시,대학로,전라북도 군산시,3.509188,38658.0,2034.631579
137,FC224454,경상북도 울진군 울진읍 연호로 47,736.0,1.0,13694.656489,91.225191,91.301527,0.000000,99.000000,13694.656489,...,0.0,0.0,1.0,경상북도,울진군,울진읍,경상북도 울진군,0.665245,1306.0,163.250000
138,FC224486,강원도 정선군 정선읍 애산로 51,612.0,1.0,5000.000000,1.250000,26.250000,0.000000,99.000000,5000.000000,...,3.0,1.0,2.0,강원도,정선군,정선읍,강원도 정선군,0.464745,12981.0,1081.750000
139,FC224494,광주광역시 광산구 상무대로 509 (우,352.0,1.0,96700.491979,44.189840,36.561497,0.000000,99.000000,96700.491979,...,0.0,0.0,0.0,광주광역시,광산구,상무대로,광주광역시 광산구,1.898192,43280.0,3934.545455
140,FC224496,광주광역시 북구 용봉로 77 (용봉동),916.0,1.0,14361.111111,1.744444,13.047222,0.000000,3.000000,14361.111111,...,NaN,NaN,NaN,광주광역시,북구,용봉로,광주광역시 북구,3.260276,40433.0,1925.380952

In [36]:
test3.isna().sum()

공연시설코드          0
주소              0
좌석수             0
예매/취소구분         0
예매/취소금액         0
예매/취소방식코드       0
결제수단코드          0
할인금액            0
할인종류코드          0
장당금액            0
년도_월            0
년도_월_일          0
년도              0
월               0
일               0
예매건수            0
취소건수            0
무료여부            0
평균좌석점유율         0
주차장             3
정류장             3
지하철출구           3
터미널             3
영화상영관           3
박물관미술관          3
도서관             3
면적10000이상공원     3
시도              0
시               0
구               0
시군구             0
전체면적대비도로면적      1
검색량합계          13
검색량평균          13
dtype: int64

In [37]:
test3[test3.검색량평균.isna()]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적,검색량합계,검색량평균
0,FC222007,경상남도 창원시 의창구 중앙대로 181,516.0,1.0,26194.652747,98.533333,98.259707,128.571429,99.000000,26323.224176,...,0.0,1.0,1.0,경상남도,창원시,의창구,경상남도 창원시,4.436285,NaN,NaN
12,FC222099,경상남도 창원시 마산회원구 삼호로 13,463.0,1.0,76136.448598,99.000000,99.000000,0.000000,99.000000,76136.448598,...,0.0,1.0,3.0,경상남도,창원시,마산회원구,경상남도 창원시,4.436285,NaN,NaN
15,FC222151,전라북도 전주시 덕진구 권삼득로 407,486.0,1.0,15625.963636,64.105455,65.834182,334.545455,99.000000,15960.509091,...,0.0,0.0,2.0,전라북도,전주시,덕진구,전라북도 전주시,7.502896,NaN,NaN
35,FC222466,경상남도 창원시 진해구 진해대로 325,964.0,1.0,36132.075472,99.000000,99.000000,0.000000,99.000000,36132.075472,...,0.0,0.0,1.0,경상남도,창원시,진해구,경상남도 창원시,4.436285,NaN,NaN
58,FC222655,세종특별자치시 조치원읍 문예회관길 22,842.0,1.0,10557.113914,35.157289,30.381236,90.853659,99.000000,10647.967572,...,0.0,1.0,2.0,세종특별자치시,조치원읍,문예회관길,세종특별자치시 조치원읍,NaN,NaN,NaN
60,FC222659,충청남도 천안시 서북구 성환읍 성진로,686.0,1.0,26623.865278,81.299653,60.383681,345.563889,98.566667,26969.429167,...,0.0,1.0,0.0,충청남도,천안시,서북구,충청남도 천안시,3.121805,NaN,NaN
67,FC222691,전라북도 전주시 완산구 팔달로 161,357.0,1.0,7359.760424,10.718428,10.051412,0.000000,99.000000,7359.760424,...,19.0,1.0,3.0,전라북도,전주시,완산구,전라북도 전주시,7.502896,NaN,NaN
69,FC222699,전라북도 전주시 덕진구 소리로 31 (,666.0,1.0,15261.846976,99.000000,99.000000,0.000000,99.000000,15261.846976,...,0.0,0.0,0.0,전라북도,전주시,덕진구,전라북도 전주시,7.502896,NaN,NaN
99,FC223313,경상북도 포항시 남구 희망대로 850,984.0,1.0,25467.528594,66.174211,34.179951,17.001546,99.000000,25484.530139,...,0.0,1.0,1.0,경상북도,포항시,남구,경상북도 포항시,2.191932,NaN,NaN
109,FC223470,충청북도 청주시 서원구 예체로 118-,710.0,1.0,23943.384515,62.752042,63.402483,444.233910,99.000000,24387.618425,...,7.0,1.0,3.0,충청북도,청주시,서원구,충청북도 청주시,3.423236,NaN,NaN
110,FC223478,경상북도 포항시 남구 시청로 1 (대잠,596.0,1.0,13566.858738,72.128668,54.451982,0.000000,99.000000,13566.858738,...,0.0,1.0,0.0,경상북도,포항시,남구,경상북도 포항시,2.191932,NaN,NaN
111,FC223485,전라북도 전주시 완산구 전주천동로 20,300.0,1.0,17531.609195,66.948276,55.666667,3465.517241,85.482759,20997.126437,...,12.0,0.0,1.0,전라북도,전주시,완산구,전라북도 전주시,7.502896,NaN,NaN
114,FC223505,충청남도 천안시 동남구 성남면 종합휴양,443.0,1.0,17226.008643,91.979994,92.312580,53.861716,98.692702,17279.870359,...,2.0,0.0,2.0,충청남도,천안시,동남구,충청남도 천안시,3.121805,NaN,NaN

In [38]:
검색량합계및평균[검색량합계및평균.시군구.str.contains("세종특별자치시")]

         시군구  검색량합계        검색량평균
98  세종특별자치시   58687  3260.388889

In [39]:
test3[test3.주소.str.contains("세종특별자치시")]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적,검색량합계,검색량평균
58,FC222655,세종특별자치시 조치원읍 문예회관길 22,842.0,1.0,10557.113914,35.157289,30.381236,90.853659,99.0,10647.967572,...,0.0,1.0,2.0,세종특별자치시,조치원읍,문예회관길,세종특별자치시 조치원읍,NaN,NaN,NaN

In [40]:
# 조인 수작업
test3['검색량합계'].iloc[12] = 6508
test3['검색량평균'].iloc[12] = 929.714286

test3['검색량합계'].iloc[37] = 12051
test3['검색량평균'].iloc[37] = 1095.545455

test3['검색량합계'].iloc[0] = 33170
test3['검색량평균'].iloc[0] = 1745.789474

test3['검색량합계'].iloc[15] = 27320
test3['검색량평균'].iloc[15] = 1437.894737

test3['검색량합계'].iloc[71] = 48650
test3['검색량평균'].iloc[71] = 1314.864865

test3['검색량합계'].iloc[73] = 27320
test3['검색량평균'].iloc[73] = 1437.894737

test3['검색량합계'].iloc[116] = 48650
test3['검색량평균'].iloc[116] = 1314.864865

test3['검색량합계'].iloc[117] = 48650
test3['검색량평균'].iloc[117] = 1314.864865

test3['검색량합계'].iloc[64] = 8687
test3['검색량평균'].iloc[64] = 789.727273

test3['검색량합계'].iloc[120] = 79005
test3['검색량평균'].iloc[120] = 3038.653846

test3['검색량합계'].iloc[114] = 249648
test3['검색량평균'].iloc[114] = 16643.200000

test3['검색량합계'].iloc[103] = 54303
test3['검색량평균'].iloc[103] = 3620.200000

test3['검색량합계'].iloc[115] = 54303
test3['검색량평균'].iloc[115] = 3620.200000

test3['검색량합계'].iloc[62] = 58687
test3['검색량평균'].iloc[62] = 3260.388889

<ipython-input-40-58ae354c22ea>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[12] = 6508
<ipython-input-40-58ae354c22ea>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[12] = 929.714286
<ipython-input-40-58ae354c22ea>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[37] = 12051
<ipython-input-40-58ae354c22ea>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[37] = 1095.545455
<ipython-input-40-58ae354c22ea>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[0] = 33170
<ipython-input-40-58ae354c22ea>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[0] = 1745.789474
<ipython-input-40-58ae354c22ea>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[15] = 27320
<ipython-input-40-58ae354c22ea>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[15] = 1437.894737
<ipython-input-40-58ae354c22ea>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[71] = 48650
<ipython-input-40-58ae354c22ea>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[71] = 1314.864865
<ipython-input-40-58ae354c22ea>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[73] = 27320
<ipython-input-40-58ae354c22ea>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[73] = 1437.894737
<ipython-input-40-58ae354c22ea>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[116] = 48650
<ipython-input-40-58ae354c22ea>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[116] = 1314.864865
<ipython-input-40-58ae354c22ea>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[117] = 48650
<ipython-input-40-58ae354c22ea>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[117] = 1314.864865
<ipython-input-40-58ae354c22ea>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[64] = 8687
<ipython-input-40-58ae354c22ea>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[64] = 789.727273
<ipython-input-40-58ae354c22ea>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[120] = 79005
<ipython-input-40-58ae354c22ea>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[120] = 3038.653846
<ipython-input-40-58ae354c22ea>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[114] = 249648
<ipython-input-40-58ae354c22ea>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[114] = 16643.200000
<ipython-input-40-58ae354c22ea>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[103] = 54303
<ipython-input-40-58ae354c22ea>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[103] = 3620.200000
<ipython-input-40-58ae354c22ea>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[115] = 54303
<ipython-input-40-58ae354c22ea>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[115] = 3620.200000
<ipython-input-40-58ae354c22ea>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량합계'].iloc[62] = 58687
<ipython-input-40-58ae354c22ea>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['검색량평균'].iloc[62] = 3260.388889

In [41]:
test3.isna().sum()

공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
주차장            3
정류장            3
지하철출구          3
터미널            3
영화상영관          3
박물관미술관         3
도서관            3
면적10000이상공원    3
시도             0
시              0
구              0
시군구            0
전체면적대비도로면적     1
검색량합계          9
검색량평균          9
dtype: int64

In [42]:
전체면적대비도로면적[전체면적대비도로면적.시군구.str.contains("인제")]

       시군구  전체면적대비도로면적
9  강원도 인제군    0.281789

In [43]:
검색량합계및평균[검색량합계및평균.시군구.str.contains("인제")]

       시군구  검색량합계       검색량평균
9  강원도 인제군   5118  465.272727

In [44]:
test3[test3.시군구.str.contains("중구")]

,공연시설코드,주소,좌석수,예매/취소구분,예매/취소금액,예매/취소방식코드,결제수단코드,할인금액,할인종류코드,장당금액,...,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적,검색량합계,검색량평균
29,FC222415,대구광역시 중구 명덕로 333 (대봉동,340.0,1.0,10858.479039,49.932378,51.350537,0.000000,99.000000,10858.479039,...,1.0,1.0,0.0,대구광역시,중구,명덕로,대구광역시 중구,12.390786,59604.0,2483.500000
30,FC222422,대구광역시 중구 봉산문화길 77 (봉산,424.0,1.0,24502.599666,37.686957,31.446823,2645.819398,99.000000,27148.419064,...,2.0,2.0,4.0,대구광역시,중구,봉산문화길,대구광역시 중구,12.390786,59604.0,2483.500000
92,FC223028,대전광역시 중구 뿌리공원로 45 (안영,400.0,1.0,11948.015123,71.092628,73.400756,1087.901701,97.003781,13035.916824,...,3.0,0.0,1.0,대전광역시,중구,뿌리공원로,대전광역시 중구,3.547540,21560.0,1026.666667
100,FC223315,대구광역시 중구 태평로 141 (태평로,660.0,1.0,1000.000000,48.717054,7.251938,0.000000,99.000000,1000.000000,...,2.0,0.0,5.0,대구광역시,중구,태평로,대구광역시 중구,12.390786,59604.0,2483.500000
117,FC223540,"울산광역시 중구 종가로 405 성안동,",499.0,1.0,7004.610951,99.000000,47.505764,387.319885,3.110663,7391.930836,...,NaN,NaN,NaN,울산광역시,중구,종가로,울산광역시 중구,5.317103,48650.0,1314.864865

In [45]:
test3.isna().sum()

공연시설코드         0
주소             0
좌석수            0
예매/취소구분        0
예매/취소금액        0
예매/취소방식코드      0
결제수단코드         0
할인금액           0
할인종류코드         0
장당금액           0
년도_월           0
년도_월_일         0
년도             0
월              0
일              0
예매건수           0
취소건수           0
무료여부           0
평균좌석점유율        0
주차장            3
정류장            3
지하철출구          3
터미널            3
영화상영관          3
박물관미술관         3
도서관            3
면적10000이상공원    3
시도             0
시              0
구              0
시군구            0
전체면적대비도로면적     1
검색량합계          9
검색량평균          9
dtype: int64

In [46]:
test3[test3.도서관.isna()].iloc[:,15:]

,예매건수,취소건수,무료여부,평균좌석점유율,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원,시도,시,구,시군구,전체면적대비도로면적,검색량합계,검색량평균
107,1.0,0.0,2.000000,0.921516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,대전광역시,유성구,대학로,대전광역시 유성구,2.204668,165366.0,6124.666667
117,1.0,0.0,1.537464,0.355777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,울산광역시,중구,종가로,울산광역시 중구,5.317103,48650.0,1314.864865
140,1.0,0.0,2.000000,0.393000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,광주광역시,북구,용봉로,광주광역시 북구,3.260276,40433.0,1925.380952

In [50]:
# test1.to_csv("join2.csv", index=False)

In [54]:
중극장조인후[중극장조인후["주소"].str.contains("북구")]

,주소,주차장,정류장,지하철출구,터미널,영화상영관,박물관미술관,도서관,면적10000이상공원
25,경상북도 포항시 북구 삼호로 533 (,0,6,0,0,0,0,1,0
56,충청남도 천안시 서북구 성환읍 성진로,1,6,0,2,0,0,1,0
93,울산광역시 북구 산업로 1000 (연암,4,15,0,0,0,0,1,2
114,광주광역시 북구 북문대로 60 (운암동,2,9,0,0,0,1,1,2
129,대구광역시 북구 구암로 47 (관음동),10,13,0,0,2,2,2,2
168,부산광역시 북구 금곡대로46번길 50,3,26,22,0,9,0,0,2
172,부산광역시 북구 낙동북로 737-1 (,1,31,2,1,0,1,1,1
185,대구광역시 북구 태평로 161 (칠성동,36,20,6,1,97,3,0,6
205,대구광역시 북구 옥산로 111 (칠성동,7,11,0,0,10,0,1,0
208,대구광역시 북구 팔달로1길 26 (노원,3,5,1,1,0,0,0,0
238,광주광역시 북구 하서로 299 (양산동,0,14,0,0,0,0,1,1
248,광주광역시 북구 필문대로 55 (풍향동,1,8,0,0,0,1,1,5
254,광주광역시 북구 첨단과기로176번길 2,0,13,0,0,20,0,0,4
258,광주광역시 북구 능안로30번길 5(오치,2,5,0,0,0,0,0,2